version: '3'

env: 
  BACKEND_IMAGE_TAG: stepordiebackend
  BACKEND_CONTAINER_NAME: stepOrDieBackend
  FRONTEND_IMAGE_TAG: stepordiefrontend
  FRONTEND_CONTAINER_NAME: stepOrDieFrontend
  FRONTEND_PORT: 4200
  BACKEND_PORT: 8081

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list

  run-backend-dev: 
    cmds:
      - cd backend && LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)) go run main.go

  run-frontend-dev:
    cmds:
      - cd frontend && ng serve

  run:
    deps: [stop]
    cmds:
      - LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1)) docker-compose up -d --build

  stop:
    cmds:
      - docker-compose down

  test-send-feedback-to-notion:
    desc: "Send a sample request to /sendFeedback (backend must be running)"
    cmds:
      - |
        curl -vX POST http://localhost:8081/api/sendFeedback \
          -H 'Content-Type: application/json' \
          --data '{"name":"Codex Tester","feedback":"Really enjoying Step or Die!"}'
