version: '3'

env: 
  BACKEND_IMAGE_TAG: notionquestbackend
  BACKEND_CONTAINER_NAME: notionQuestBackend
  FRONTEND_IMAGE_TAG: notionquestfrontend
  FRONTEND_CONTAINER_NAME: notionQuestFrontend
  FRONTEND_PORT: 4200
  BACKEND_PORT: 8080

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list

  run-backend-dev: 
    cmds:
      - cd backend && go run main.go

  run-frontend-dev:
    cmds:
      - cd frontend && ng serve

  stop-backend:
    cmds:
      - docker stop {{.BACKEND_CONTAINER_NAME}} || true
      - docker rm {{.BACKEND_CONTAINER_NAME}} || true

  stop-frontend:
    cmds:
      - docker stop {{.FRONTEND_CONTAINER_NAME}} || true
      - docker rm {{.FRONTEND_CONTAINER_NAME}} || true

  build-backend:
    cmds: 
      - docker image rm {{.BACKEND_IMAGE_TAG}} || true
      - docker build -t {{.BACKEND_IMAGE_TAG}} ./backend

  build-frontend:
    cmds:
      - docker image rm {{.FRONTEND_IMAGE_TAG}} || true
      - docker build -t {{.FRONTEND_IMAGE_TAG}} ./frontend

  run-backend:  
    deps: [stop-backend, build-backend]
    cmds:
    - docker run -d -p {{.BACKEND_PORT}}:{{.BACKEND_PORT}} --name {{.BACKEND_CONTAINER_NAME}} {{.BACKEND_IMAGE_TAG}}

  run-frontend:
    deps: [stop-frontend, build-frontend]
    cmds:
      - docker run -d -p {{.FRONTEND_PORT}}:{{.FRONTEND_PORT}} --name {{.FRONTEND_CONTAINER_NAME}} {{.FRONTEND_IMAGE_TAG}}

  run:
    deps: [stop, build-backend, build-frontend]
    cmds:
      - docker-compose up -d

  stop:
    cmds:
      - docker-compose down

  test-load-game-state-from-notion:
    desc: "Send a sample request to /loadGameStateFromNotion (backend must be running)"
    cmds:
      - |
        curl -vX POST http://localhost:8080/api/loadGameStateFromNotion \
          -H 'Content-Type: application/json' \
          --data '{"notionUrl":"https://fabiansieper.notion.site/Notion-Quest-2c25e55239fb80f78f9df3fa2c2d65d1"}'
