export enum DialogType {
  LOADING = 'LOADING',
  WON = 'WON',
  LOST = 'LOST',
  NOT_FOUND = 'NOT_FOUND',
  BACKEND_ERROR = 'BACKEND_ERROR',
  SUCCESS = 'SUCCESS',
  DUPLICATE_FOUND = 'DUPLICATE_FOUND',
  NOTION_URL_EMPTY = 'NOTION_URL_EMPTY',
  INVALID_NOTION_URL = 'INVALID_NOTION_URL',
  ARE_YOU_SURE = 'ARE_YOU_SURE',
}
